[package]
name = "sprockets-host"
version = "0.1.0"
edition = "2021"

[dependencies]
sprockets-rot = { path = "../rot" }
ring = "0.16.20"
hubpack = { rev = "df08cc3a6e1f97381cd0472ae348e310f0119e25", git = "https://github.com/cbiffle/hubpack.git"}
derive_more = "0.99.17"
serde = { version = "1.0.136", features = ["derive"]  }
serde-big-array = { version = "0.3.2" }
